apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: registry
  namespace: kube-system
data:
  config.yml: |
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
      filesystem:
        rootdirectory: /var/lib/registry
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
    notifications:
      endpoints:
        - name: argoos
          url: http://argoos/event
          headers:
            X-Argoos-Registry-Name: ["localhost"]
          timeout: 500ms
          threshold: 5
          backoff: 1s

# vim:ft=yaml:et:sw=2:ts=2:sts=2:
