apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: kube-system
  labels:
    app: registry
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "KubeRegistry"
spec:
  selector:
    app: registry
  ports:
  - name: registry
    port: 5000
    protocol: TCP

# vim:ft=yaml:et:sw=2:ts=2:sts=2:
